### PR TITLE
Delta updates support

### PR DESCRIPTION
**Pull request by brandonkelly**
Hey Josh,

Craft 3.4 is adding support for **delta element updates** (craftcms/cms#5146), meaning that entry, category, and user forms will only submit custom field values that actually changed, giving the back end a chance to optimize the element save process by avoiding saving things that haven’t changed.

Matrix already supports it, and this PR adds support for Super Table as well.

Hoping that you can create a new `2.4` or `craft-3.4`  branch, swap the PR’s base branch over to that, and then merge this in, so people have a way to start testing.

To get Craft 3.4 running locally, change your `craftcms/cms` requirement in `composer.json` to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev",
  "...": "..."
}
```

Then run `composer update`.

Let me know if you have any questions!

### CODE REVIEW

**Comment by engram-design** [comment]
Neat! Thanks @brandonkelly

**Comment by engram-design** [comment]
@brandonkelly Closing this PR, but added as a new branch https://github.com/verbb/super-table/tree/feature/delta-updates - if I knew a nicer way to handle this in Github, that's be nice, but can't figure out how to create a new branch from a PR.

Anyway, thanks for being awesome!

**Comment by brandonkelly** [comment]
@engram-design FFR you can change the PR’s base branch by clicking the Edit button at the top.

**Comment by engram-design** [comment]
@brandonkelly Ohhh, I knew it'd be something like that. Nice one!

**Pull request closed without merging**
