### PR TITLE
Sliding animation when adding/deleting row blocks

### PR DESCRIPTION
**Pull request by benjamminf**
Just something minor. Added a transition to row blocks like with the Matrix field.

### CODE REVIEW

**Comment by benjamminf** [comment]
Accidentally new-lined my curly braces in the functions (fixed now). And I was so careful to use spaces instead of tabs...

**Comment by engram-design** [comment]
Sorry for not responding sooner @benjamminf just wanted to test this out. Its super-slick, so thanks!!

**Comment by benjamminf** [comment]
Awesome! No problem at all, I know how hard it is to keep up with side projects :) Just updated to 1.x and I'm very impressed with the updates! Love the new field editor.

**Comment by engram-design** [comment]
Thanks @benjamminf , really wasn't happy with the modal settings, so hopefully this is an improvement for the moment. Thanks again!

**Pull request closed without merging**
